// ============================================================
//  PERFUMES DE LA COLECCIÓN — Al Eutur Perfumes
//  Cada bloque { ... } es una ficha. El orden de esta lista es
//  el orden en que aparecen en la web.
//
//  seccion  : arabe | disenador
//  genero   : hombre (incluye unisex) | mujer   (mujer va a la sección Mujer)
//  cat      : fresco | oriental | amaderado | gourmand   (filtro)
//  encargue : true muestra la etiqueta "Por encargue"
//  img      : foto en img/perfumes/  (fondo transparente, .webp)
//  il/insp  : "Inspirado en" + perfume de referencia
//
//  Instrucciones completas en el README.md
// ============================================================
window.PERFUMES = [
  {
    "k": "mandarin",
    "name": "Odyssey Mandarin Sky",
    "brand": "Armaf",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Cítrica dulce",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/mandarin.webp",
    "desc": "Mandarina fresca y azafrán dan paso a un fondo de caramelo suave. Adictivo, luminoso, ideal para el día.",
    "top": "Mandarina · Notas verdes",
    "heart": "Azafrán · Flor de naranjo",
    "base": "Caramelo · Almizcle · Cedro",
    "il": "Inspirado en",
    "insp": "Scandal Pour Homme · Jean Paul Gaultier"
  },
  {
    "k": "spectra",
    "name": "Odyssey Spectra",
    "brand": "Armaf",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Oriental especiada",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/spectra.webp",
    "desc": "Manzana y canela envuelven un corazón de tabaco especiado. Dulce, magnético, pensado para la noche.",
    "top": "Manzana · Canela",
    "heart": "Tabaco · Especias",
    "base": "Vainilla · Ámbar · Maderas",
    "il": "Inspirado en",
    "insp": "Le Male Le Parfum · Jean Paul Gaultier"
  },
  {
    "k": "homme",
    "name": "Odyssey Homme",
    "brand": "Armaf",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Oriental amaderada",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/homme.webp",
    "desc": "Cardamomo y sándalo sobre un fondo cálido de vainilla y ámbar. Elegante, envolvente, para ocasiones nocturnas.",
    "top": "Cardamomo · Bergamota",
    "heart": "Sándalo · Especias",
    "base": "Vainilla · Ámbar · Cachemira",
    "il": "Inspirado en",
    "insp": "Noir Extreme · Tom Ford"
  },
  {
    "k": "dubai",
    "name": "Odyssey Dubai Chocolat",
    "brand": "Armaf",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Gourmand",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/dubai.webp",
    "desc": "El postre viral hecho perfume. Pistacho cremoso, café y praliné sobre un fondo dulce y envolvente.",
    "top": "Pistacho · Café",
    "heart": "Praliné · Cacao",
    "base": "Caramelo · Haba tonka · Amberwood",
    "il": "Inspiración",
    "insp": "El famoso chocolate de Dubái"
  },
  {
    "k": "honor",
    "name": "Honor & Glory",
    "brand": "Lattafa",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Ámbar gourmand",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/honor.webp",
    "desc": "Piña jugosa y crème brûlée sobre un fondo ambarado. Unisex, dulce con presencia, para todo el año.",
    "top": "Piña · Bergamota",
    "heart": "Crème brûlée · Flores blancas",
    "base": "Ámbar · Almizcle · Maderas",
    "il": "Inspiración",
    "insp": "Gourmand ámbar de firma"
  },
  {
    "k": "toscano",
    "name": "Toscano Leather",
    "brand": "Maison Alhambra",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Cuero",
    "cat": "amaderado",
    "encargue": false,
    "img": "img/perfumes/toscano.webp",
    "desc": "Cuero intenso realzado por azafrán y un toque de frambuesa. Elegante, de carácter, para la noche o el frío.",
    "top": "Azafrán · Tomillo",
    "heart": "Cuero · Frambuesa · Incienso",
    "base": "Cuero · Ámbar",
    "il": "Inspirado en",
    "insp": "Tuscan Leather · Tom Ford"
  },
  {
    "k": "bharara",
    "name": "Bharara King",
    "brand": "Bharara",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Aromática afrutada",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/bharara.webp",
    "desc": "Cítricos radiantes sobre un fondo dulce y ambarado. Proyección enorme, unisex, para destacar en cualquier evento.",
    "top": "Bergamota · Cítricos",
    "heart": "Frutas · Flores blancas",
    "base": "Vainilla · Ámbar · Almizcle",
    "il": "Inspirado en",
    "insp": "Erba Pura · Xerjoff"
  },
  {
    "k": "yeah",
    "name": "Yeah! Parfum",
    "brand": "Maison Alhambra",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Ámbar aromática",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/yeah.webp",
    "desc": "Manzana y jengibre dan paso a un fondo cálido de ámbar y tonka. Más intenso que la versión EDP, ideal para clima fresco.",
    "top": "Manzana · Jengibre",
    "heart": "Lavanda · Especias",
    "base": "Ámbar · Haba tonka · Maderas",
    "il": "Inspirado en",
    "insp": "Y Le Parfum · Yves Saint Laurent"
  },
  {
    "k": "sceptre",
    "name": "Sceptre Malachite",
    "brand": "Maison Alhambra",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Amaderada verde",
    "cat": "amaderado",
    "encargue": false,
    "img": "img/perfumes/sceptre.webp",
    "desc": "Verde aromático sobrio con fondo de vetiver y pachulí. Atemporal, ideal para oficina y uso diario.",
    "top": "Bergamota · Notas verdes",
    "heart": "Geranio · Especias",
    "base": "Vetiver · Pachulí · Maderas",
    "il": "Inspirado en",
    "insp": "Le Gemme Malachite · Bvlgari"
  },
  {
    "k": "baroque",
    "name": "Baroque Rouge 540",
    "brand": "Maison Alhambra",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Ámbar floral",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/baroque.webp",
    "desc": "La estela más reconocida del mundo, reinterpretada. Azafrán y jazmín sobre amberwood cálido. El más deseado de la casa.",
    "top": "Azafrán · Jazmín",
    "heart": "Amberwood · Flores blancas",
    "base": "Ámbar gris · Cedro",
    "il": "Inspirado en",
    "insp": "Baccarat Rouge 540 · Maison Francis Kurkdjian"
  },
  {
    "k": "victorioso",
    "name": "Victorioso",
    "brand": "Maison Alhambra",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Aromática acuática amaderada",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/victorioso.webp",
    "desc": "Pomelo y notas marinas abren con frescura vibrante sobre una base amaderada. Enérgico y versátil para el día.",
    "top": "Pomelo · Notas marinas",
    "heart": "Laurel · Jazmín · Hedione",
    "base": "Gaiac · Musgo de roble · Ámbar gris",
    "il": "Inspirado en",
    "insp": "Invictus · Paco Rabanne"
  },
  {
    "k": "tag",
    "name": "Tag Uomo Nero",
    "brand": "Armaf",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Amaderada aromática",
    "cat": "amaderado",
    "encargue": false,
    "img": "img/perfumes/tag.webp",
    "desc": "Apertura especiada con un corazón floral inesperado de violeta y rosa. Elegante y versátil, mejora con maceración.",
    "top": "Bergamota · Pimienta negra · Lavanda",
    "heart": "Lirio del valle · Violeta · Rosa",
    "base": "Pachulí · Ámbar gris · Vainilla",
    "il": "Inspirado en",
    "insp": "Tuxedo · Yves Saint Laurent"
  },
  {
    "k": "salvo",
    "name": "Salvo Elixir",
    "brand": "Maison Alhambra",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Aromática especiada",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/salvo.webp",
    "desc": "Especiado y potente desde el primer momento. Canela y cardamomo sobre un fondo ambarado, para clima frío.",
    "top": "Canela · Cardamomo",
    "heart": "Lavanda · Especias",
    "base": "Ámbar · Maderas · Almizcle",
    "il": "Inspirado en",
    "insp": "Sauvage Elixir · Dior"
  },
  {
    "k": "mega",
    "name": "Odyssey Mega",
    "brand": "Armaf",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Aromática amaderada",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/mega.webp",
    "desc": "Fresco, limpio y fácil de llevar. Jengibre y cítricos sobre un fondo suave de cedro. Ideal día a día.",
    "top": "Jengibre · Bergamota · Cítricos",
    "heart": "Piña · Salvia · Enebro",
    "base": "Almizcle · Cedro · Haba tonka",
    "il": "Inspirado en",
    "insp": "Y Eau de Parfum · Yves Saint Laurent"
  },
  {
    "k": "momento",
    "name": "Momento",
    "brand": "Riiffs",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Amaderada especiada",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/momento.webp",
    "desc": "Azafrán y rosa sobre un fondo dulce de tonka. Amaderado y elegante, con gran duración.",
    "top": "Azafrán · Rosa",
    "heart": "Especias · Flores",
    "base": "Haba tonka · Maderas · Ámbar",
    "il": "Inspirado en",
    "insp": "Arabians Tonka · Montale"
  },
  {
    "k": "clubdenuit",
    "name": "Club de Nuit Intense Man",
    "brand": "Armaf",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Amaderada ahumada",
    "cat": "amaderado",
    "encargue": false,
    "img": "img/perfumes/clubdenuit.webp",
    "desc": "Piña y frutas abren paso a un fondo ahumado de abedul. Intenso y versátil, con proyección excepcional en modo bestia.",
    "top": "Piña · Manzana · Bergamota",
    "heart": "Abedul · Jazmín",
    "base": "Almizcle · Ámbar · Maderas",
    "il": "Inspirado en",
    "insp": "Aventus · Creed"
  },
  {
    "k": "asadelixir",
    "name": "Asad Elixir",
    "brand": "Lattafa",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Oriental ahumada",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/asadelixir.webp",
    "desc": "Azafrán y tabaco sobre un fondo de incienso y ámbar seco. Nocturno y elegante, para las estaciones frías.",
    "top": "Pimienta rosa · Azafrán · Pomelo",
    "heart": "Tabaco · Cedro · Vainilla",
    "base": "Incienso · Ámbar · Pachulí",
    "il": "Inspiración",
    "insp": "Perfil ahumado y especiado, ideal para clima frío"
  },
  {
    "k": "asadbourbon",
    "name": "Asad Bourbon",
    "brand": "Lattafa",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Ámbar gourmand",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/asadbourbon.webp",
    "desc": "Cacao y vainilla bourbon envuelven un corazón especiado. Cálido, dulce y unisex, perfecto para el invierno.",
    "top": "Lavanda · Ciruela · Pimienta rosa",
    "heart": "Cacao · Nuez moscada · Davana",
    "base": "Vainilla bourbon · Ámbar · Vetiver",
    "il": "Inspiración",
    "insp": "Cálido y goloso, ideal para noches frescas"
  },
  {
    "k": "cdnwoman",
    "name": "Club de Nuit Woman",
    "brand": "Armaf",
    "seccion": "arabe",
    "genero": "mujer",
    "fam": "Chipre floral",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/cdnwoman.webp",
    "desc": "Cítrico chispeante sobre rosa y pachulí. Fresco, elegante y sofisticado, de día o de noche. Para damas.",
    "top": "Naranja · Bergamota · Toronja",
    "heart": "Rosa · Pachulí",
    "base": "Almizcle · Maderas",
    "il": "Inspirado en",
    "insp": "Coco Mademoiselle · Chanel"
  },
  {
    "k": "cdnintensew",
    "name": "Club de Nuit Intense Woman",
    "brand": "Armaf",
    "seccion": "arabe",
    "genero": "mujer",
    "fam": "Floral oriental",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/cdnintensew.webp",
    "desc": "La versión femenina del clásico Intense: rosa, azafrán y oud. Estela fuerte, ideal para la noche. Para damas.",
    "top": "Rosa · Fresco especiado",
    "heart": "Azafrán · Pachulí",
    "base": "Oud · Vainilla · Ámbar",
    "il": "Inspirado en",
    "insp": "Noir de Noir · Tom Ford"
  },
  {
    "k": "maleka",
    "name": "Club de Nuit Maleka",
    "brand": "Armaf",
    "seccion": "arabe",
    "genero": "mujer",
    "fam": "Floral frutal",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/maleka.webp",
    "desc": "Lichi jugoso e iris atalcado sobre un fondo de praliné y sándalo. Dulce y refinado, 7 h de duración. Para damas.",
    "top": "Lichi · Bergamota",
    "heart": "Iris · Raíz de lirio",
    "base": "Praliné · Sándalo · Ambroxan",
    "il": "Inspirado en",
    "insp": "Delina · Parfums de Marly"
  },
  {
    "k": "untold",
    "name": "Club de Nuit Untold",
    "brand": "Armaf",
    "seccion": "arabe",
    "genero": "mujer",
    "fam": "Ámbar amaderado",
    "cat": "amaderado",
    "encargue": false,
    "img": "img/perfumes/untold.webp",
    "desc": "Azafrán y ámbar gris sobre maderas luminosas. Unisex, dulce y metálico, con 8 h de duración y estela fuerte.",
    "top": "Azafrán · Jazmín",
    "heart": "Madera de ámbar · Ámbar gris",
    "base": "Cedro · Abeto",
    "il": "Inspirado en",
    "insp": "Baccarat Rouge 540 · MFK"
  },
  {
    "k": "iconic",
    "name": "Club de Nuit Blue Iconic",
    "brand": "Armaf",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Amaderada fresca",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/iconic.webp",
    "desc": "Cítricos y menta sobre maderas secas e incienso. Fresco, versátil y masculino. Frasco de 125 ml.",
    "top": "Pomelo · Limón · Menta",
    "heart": "Jengibre · Pimienta rosa",
    "base": "Incienso · Sándalo · Cedro",
    "il": "Inspirado en",
    "insp": "Bleu de Chanel · Chanel"
  },
  {
    "k": "yara",
    "name": "Yara",
    "brand": "Lattafa",
    "seccion": "arabe",
    "genero": "mujer",
    "fam": "Vainilla gourmand",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/yara.webp",
    "desc": "Dulce, cremoso y afrutado desde el primer instante. El favorito femenino de Lattafa, coqueto y fácil de llevar.",
    "top": "Mandarina · Orquídea · Heliotropo",
    "heart": "Acorde gourmand · Frutas tropicales",
    "base": "Vainilla · Musk · Sándalo",
    "il": "Inspiración",
    "insp": "Creación de firma · el gourmand femenino más vendido de Lattafa"
  },
  {
    "k": "yaramoi",
    "name": "Yara Moi",
    "brand": "Lattafa",
    "seccion": "arabe",
    "genero": "mujer",
    "fam": "Floral amaderada",
    "cat": "amaderado",
    "encargue": false,
    "img": "img/perfumes/yaramoi.webp",
    "desc": "La Yara blanca: jazmín y durazno sobre sándalo y caramelo. Más elegante y versátil que el resto de la línea. Para damas.",
    "top": "Jazmín · Durazno",
    "heart": "Pachulí · Cálido especiado",
    "base": "Sándalo · Caramelo · Ámbar",
    "il": "Inspirado en",
    "insp": "Perfect Intense · Marc Jacobs"
  },
  {
    "k": "yaraelixir",
    "name": "Yara Elixir",
    "brand": "Lattafa",
    "seccion": "arabe",
    "genero": "mujer",
    "fam": "Oriental vainilla",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/yaraelixir.webp",
    "desc": "El más goloso de la línea Yara: frutilla, caramelo y vainilla. Dulce, envolvente y de estela fuerte. Para damas.",
    "top": "S'mores de frutilla · Grosella negra",
    "heart": "Caramelo · Floral blanco",
    "base": "Vainilla · Ámbar · Almizcle",
    "il": "Inspirado en",
    "insp": "Black Opium · YSL"
  },
  {
    "k": "yaratous",
    "name": "Yara Tous",
    "brand": "Lattafa",
    "seccion": "arabe",
    "genero": "mujer",
    "fam": "Tropical dulce",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/yaratous.webp",
    "desc": "Mango, coco y maracuyá sobre una vainilla cremosa. Veraniego, alegre y con mucha estela.",
    "top": "Mango · Coco · Maracuyá",
    "heart": "Jazmín · Flor de azahar",
    "base": "Vainilla · Almizcle",
    "il": "Inspirado en",
    "insp": "Fame · Paco Rabanne"
  },
  {
    "k": "yaracandy",
    "name": "Yara Candy",
    "brand": "Lattafa",
    "seccion": "arabe",
    "genero": "mujer",
    "fam": "Frutal dulce",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/yaracandy.webp",
    "desc": "Caramelo efervescente y grosella negra con un fondo de vainilla. Juvenil, goloso y muy llamativo.",
    "top": "Mandarina verde · Grosella negra",
    "heart": "Caramelo efervescente · Gardenia",
    "base": "Vainilla · Almizcle",
    "il": "Inspiración",
    "insp": "Creación de firma · la versión más golosa de la línea Yara"
  },
  {
    "k": "kingdom",
    "name": "The Kingdom",
    "brand": "Lattafa",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Oriental aromática",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/kingdom.webp",
    "desc": "Lavanda y menta abren paso a un corazón de tabaco y vainilla. Dulce, envolvente y de mucha presencia.",
    "top": "Lavanda · Menta · Salvia",
    "heart": "Vainilla · Tabaco · Flor de azahar",
    "base": "Haba tonka · Benjuí · Ládano",
    "il": "Inspirado en",
    "insp": "Le Male Elixir · Jean Paul Gaultier"
  },
  {
    "k": "vintageradio",
    "name": "Vintage Radio",
    "brand": "Lattafa",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Amaderada aromática",
    "cat": "amaderado",
    "encargue": false,
    "img": "img/perfumes/vintageradio.webp",
    "desc": "Lavanda y bergamota frescas sobre ciruela, palo santo y oud. Elegante, distinto y fácil de llevar.",
    "top": "Lavanda · Salvia · Bergamota",
    "heart": "Ciruela · Palo santo · Pimienta negra",
    "base": "Sándalo · Oud",
    "il": "Inspirado en",
    "insp": "Paragon · Initio"
  },
  {
    "k": "khamrah",
    "name": "Khamrah",
    "brand": "Lattafa",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Oriental gourmand",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/khamrah.webp",
    "desc": "Dátiles y canela sobre un fondo de praliné y vainilla. Dulce, cálido y envolvente. Disponible por encargue.",
    "top": "Dátiles · Canela",
    "heart": "Praliné · Especias",
    "base": "Vainilla · Ámbar · Maderas",
    "il": "Inspiración",
    "insp": "Creación de firma de la línea Khamrah"
  },
  {
    "k": "khamrah_qahwa",
    "name": "Khamrah Qahwa",
    "brand": "Lattafa",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Oriental vainilla",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/khamrah_qahwa.webp",
    "desc": "Café y cardamomo sobre vainilla y tonka. Cálido y adictivo. Disponible por encargue.",
    "top": "Café · Cardamomo",
    "heart": "Praliné · Especias",
    "base": "Vainilla · Tonka · Maderas",
    "il": "Inspiración",
    "insp": "Variante café de la línea Khamrah"
  },
  {
    "k": "khamrah_dukhan",
    "name": "Khamrah Dukhan",
    "brand": "Lattafa",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Oriental ahumado",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/khamrah_dukhan.webp",
    "desc": "Ahumado y de carácter, con tabaco e incienso sobre fondo amaderado. Oscuro y elegante. Disponible por encargue.",
    "top": "Especias · Ahumado",
    "heart": "Tabaco · Incienso",
    "base": "Maderas · Ámbar",
    "il": "Inspiración",
    "insp": "Variante ahumada de la línea Khamrah"
  },
  {
    "k": "khamrah_waha",
    "name": "Khamrah Waha",
    "brand": "Lattafa",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Fresco acuático",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/khamrah_waha.webp",
    "desc": "El más ligero e inesperado de la línea Khamrah: fresco y acuático. Novedad 2026. Disponible por encargue.",
    "top": "Notas acuáticas · Cítricos",
    "heart": "Flores blancas",
    "base": "Almizcle · Maderas claras",
    "il": "Inspiración",
    "insp": "La variante fresca que rompe el ADN cálido de la línea"
  },
  {
    "k": "aquadubai",
    "name": "Amber Oud Aqua Dubai",
    "brand": "Al Haramain",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Ámbar acuático",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/aquadubai.webp",
    "desc": "Fresco y ambarado, con una firma acuática distintiva. Elegante y luminoso. Disponible por encargue, 100ml.",
    "top": "Cítricos · Notas acuáticas",
    "heart": "Flores",
    "base": "Ámbar · Maderas",
    "il": "Inspirado en",
    "insp": "Imagination · Louis Vuitton"
  },
  {
    "k": "goldedition",
    "name": "Amber Oud Gold Edition",
    "brand": "Al Haramain",
    "seccion": "arabe",
    "genero": "hombre",
    "fam": "Ámbar afrutado",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/goldedition.webp",
    "desc": "Cítricos y frutas sobre vainilla y ámbar cálido. Dulce y radiante. Disponible por encargue, 100ml.",
    "top": "Cítricos · Frutas",
    "heart": "Flores blancas",
    "base": "Vainilla · Ámbar · Maderas",
    "il": "Inspirado en",
    "insp": "Erba Pura · Xerjoff"
  },
  {
    "k": "adg_edp",
    "name": "Acqua di Giò EDP",
    "brand": "Giorgio Armani",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Acuática aromática",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/adg_edp.webp",
    "desc": "El clásico marino de Armani en versión más intensa y duradera. Fresco, limpio y elegante para todos los días.",
    "top": "Mandarina verde · Notas marinas",
    "heart": "Salvia · Lavanda · Geranio",
    "base": "Notas minerales · Pachulí · Vetiver",
    "il": "Presentación",
    "insp": "Original · 100 ml"
  },
  {
    "k": "adg_profondo_edp",
    "name": "Acqua di Giò Profondo EDP",
    "brand": "Giorgio Armani",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Acuática aromática",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/adg_profondo_edp.webp",
    "desc": "La cara más profunda de Acqua di Giò: marino, aromático y con un fondo mineral que dura.",
    "top": "Notas marinas · Bergamota · Mandarina verde",
    "heart": "Romero · Lavanda · Ciprés",
    "base": "Pachulí · Almizcle · Ámbar",
    "il": "Presentación",
    "insp": "Original · 100 ml"
  },
  {
    "k": "adg_profondo_parfum",
    "name": "Acqua di Giò Profondo Parfum",
    "brand": "Giorgio Armani",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Acuática ambarada",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/adg_profondo_parfum.webp",
    "desc": "La concentración más alta de la línea Profondo. Marino al abrir, cálido y envolvente en el fondo.",
    "top": "Notas marinas · Mandarina verde",
    "heart": "Mimosa",
    "base": "Pachulí · Ládano",
    "il": "Presentación",
    "insp": "Original · 100 ml"
  },
  {
    "k": "armani_code",
    "name": "Armani Code EDP",
    "brand": "Giorgio Armani",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Aromática ambarada",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/armani_code.webp",
    "desc": "Seductor y pulido: salvia e iris sobre una haba tonka cálida. Un clásico nocturno renovado.",
    "top": "Bergamota",
    "heart": "Salvia · Iris · Aldehídos",
    "base": "Haba tonka · Cedro",
    "il": "Presentación",
    "insp": "Original · 125 ml"
  },
  {
    "k": "val_uomo_intense",
    "name": "Uomo Born in Roma Intense",
    "brand": "Valentino",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Ambarada avainillada",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/val_uomo_intense.webp",
    "desc": "Vainilla y lavanda con un fondo de vetiver. Dulce, potente y de los más elogiados de Valentino.",
    "top": "Vainilla",
    "heart": "Lavanda",
    "base": "Vetiver",
    "il": "Presentación",
    "insp": "Original · 100 ml"
  },
  {
    "k": "val_uomo_extradose",
    "name": "Uomo Born in Roma Extradose",
    "brand": "Valentino",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Fougère amaderada",
    "cat": "amaderado",
    "encargue": false,
    "img": "img/perfumes/val_uomo_extradose.webp",
    "desc": "La versión más intensa de la línea para hombre: especias, lavandín y vetiver en concentración parfum.",
    "top": "Acorde de especias",
    "heart": "Lavandín",
    "base": "Vetiver",
    "il": "Presentación",
    "insp": "Original · 100 ml"
  },
  {
    "k": "val_coral",
    "name": "Uomo Born in Roma Coral Fantasy",
    "brand": "Valentino",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Frutal aromática",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/val_coral.webp",
    "desc": "Manzana roja y cardamomo con un fondo de tabaco suave. Fresco, juvenil y muy versátil.",
    "top": "Manzana roja · Cardamomo",
    "heart": "Salvia · Lavanda",
    "base": "Tabaco · Pachulí",
    "il": "Presentación",
    "insp": "Original · 100 ml"
  },
  {
    "k": "val_donna_intense",
    "name": "Donna Born in Roma Intense",
    "brand": "Valentino",
    "seccion": "disenador",
    "genero": "mujer",
    "fam": "Ambarada avainillada",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/val_donna_intense.webp",
    "desc": "Jazmín envuelto en vainilla bourbon y benjuí. Femenino, cálido y con mucha estela.",
    "top": "Vainilla bourbon",
    "heart": "Jazmín",
    "base": "Benjuí",
    "il": "Presentación",
    "insp": "Original · 100 ml"
  },
  {
    "k": "val_donna_extradose",
    "name": "Donna Born in Roma Extradose",
    "brand": "Valentino",
    "seccion": "disenador",
    "genero": "mujer",
    "fam": "Floral avainillada",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/val_donna_extradose.webp",
    "desc": "La versión más intensa para mujer: cassis jugoso, un toque de ron y extracto de vainilla.",
    "top": "Acorde de cassis",
    "heart": "Acorde de ron",
    "base": "Extracto de vainilla",
    "il": "Presentación",
    "insp": "Original · 100 ml"
  },
  {
    "k": "invictus",
    "name": "Invictus EDT",
    "brand": "Rabanne",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Acuática amaderada",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/invictus.webp",
    "desc": "Pomelo y notas marinas sobre maderas. Fresco, deportivo y uno de los más vendidos del mundo.",
    "top": "Pomelo · Notas marinas · Mandarina",
    "heart": "Hoja de laurel · Jazmín",
    "base": "Madera de guayaco · Musgo de roble · Pachulí",
    "il": "Presentación",
    "insp": "Original · 100 ml"
  },
  {
    "k": "invictus_victory_elixir",
    "name": "Invictus Victory Elixir",
    "brand": "Rabanne",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Ambarada especiada",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/invictus_victory_elixir.webp",
    "desc": "La versión más potente de Invictus: especias, incienso y vainilla. Ideal para la noche y el frío.",
    "top": "Pimienta negra · Bergamota · Cardamomo",
    "heart": "Incienso · Lavanda · Vainilla",
    "base": "Haba tonka · Pachulí · Almizcle",
    "il": "Presentación",
    "insp": "Original · 100 ml"
  },
  {
    "k": "million_elixir",
    "name": "1 Million Elixir",
    "brand": "Rabanne",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Ambarada amaderada",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/million_elixir.webp",
    "desc": "Manzana y rosa damascena sobre vainilla y haba tonka. Más oscuro y elegante que el 1 Million clásico.",
    "top": "Davana · Manzana",
    "heart": "Rosa damascena · Osmanthus",
    "base": "Haba tonka · Vainilla · Pachulí · Cedro",
    "il": "Presentación",
    "insp": "Original · 100 ml"
  },
  {
    "k": "dylan_blue",
    "name": "Dylan Blue EDT",
    "brand": "Versace",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Aromática fougère",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/dylan_blue.webp",
    "desc": "Cítricos y notas acuáticas con un fondo de incienso y ambroxan. Fresco, masculino y muy rendidor.",
    "top": "Bergamota · Pomelo · Hoja de higuera",
    "heart": "Hoja de violeta · Pachulí · Pimienta negra",
    "base": "Incienso · Almizcle · Haba tonka",
    "il": "Presentación",
    "insp": "Original · 100 ml"
  },
  {
    "k": "versace_pour_homme",
    "name": "Versace Pour Homme",
    "brand": "Versace",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Aromática cítrica",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/versace_pour_homme.webp",
    "desc": "Limón y neroli sobre un fondo limpio de almizcle. Mediterráneo, prolijo y perfecto para el día.",
    "top": "Limón · Bergamota · Neroli",
    "heart": "Jacinto · Salvia · Cedro",
    "base": "Haba tonka · Almizcle · Ámbar",
    "il": "Presentación",
    "insp": "Original · 100 ml"
  },
  {
    "k": "sauvage_edp",
    "name": "Sauvage EDP",
    "brand": "Dior",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Especiada ambarada",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/sauvage_edp.webp",
    "desc": "Bergamota fresca, pimienta y un fondo de ambroxan y vainilla. Potente, reconocible y siempre elogiado.",
    "top": "Bergamota de Calabria",
    "heart": "Pimienta de Sichuan · Lavanda · Anís estrellado",
    "base": "Ambroxan · Vainilla",
    "il": "Presentación",
    "insp": "Original · 100 ml"
  },
  {
    "k": "dior_homme_sport",
    "name": "Dior Homme Sport",
    "brand": "Dior",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Cítrica amaderada",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/dior_homme_sport.webp",
    "desc": "Limón y bergamota vibrantes con pimienta rosa y un fondo amaderado. Fresco, enérgico y prolijo.",
    "top": "Limón · Bergamota · Aldehídos",
    "heart": "Pimienta rosa · Elemí",
    "base": "Notas amaderadas · Incienso · Ámbar",
    "il": "Presentación",
    "insp": "Original · consultá presentaciones"
  },
  {
    "k": "myslf",
    "name": "MYSLF EDP",
    "brand": "Yves Saint Laurent",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Floral amaderada",
    "cat": "amaderado",
    "encargue": false,
    "img": "img/perfumes/myslf.webp",
    "desc": "Flor de azahar luminosa sobre maderas y pachulí. Moderno, limpio y muy elegante.",
    "top": "Bergamota de Calabria",
    "heart": "Flor de azahar de Túnez",
    "base": "Pachulí · Ambrofix",
    "il": "Presentación",
    "insp": "Original · 100 ml"
  },
  {
    "k": "y_edp",
    "name": "Y EDP",
    "brand": "Yves Saint Laurent",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Aromática fougère",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/y_edp.webp",
    "desc": "Manzana y jengibre al abrir, salvia en el corazón y un fondo amaderado. Fresco con mucha duración.",
    "top": "Manzana · Jengibre · Bergamota",
    "heart": "Salvia · Bayas de enebro · Geranio",
    "base": "Amberwood · Haba tonka · Cedro",
    "il": "Presentación",
    "insp": "Original · 100 ml"
  },
  {
    "k": "lemale_elixir",
    "name": "Le Male Elixir",
    "brand": "Jean Paul Gaultier",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Ambarada fougère",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/lemale_elixir.webp",
    "desc": "Lavanda y menta sobre miel, vainilla y tabaco. Dulce, sensual y de gran estela.",
    "top": "Lavanda · Menta",
    "heart": "Vainilla · Benjuí",
    "base": "Miel · Haba tonka · Tabaco",
    "il": "Presentación",
    "insp": "Original · 100 ml"
  },
  {
    "k": "lemale_parfum",
    "name": "Le Male Le Parfum",
    "brand": "Jean Paul Gaultier",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Ambarada amaderada",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/lemale_parfum.webp",
    "desc": "Cardamomo, lavanda e iris sobre una vainilla profunda. La versión más elegante y oscura de Le Male.",
    "top": "Cardamomo",
    "heart": "Lavanda · Iris",
    "base": "Vainilla · Notas orientales · Maderas",
    "il": "Presentación",
    "insp": "Original · consultá presentaciones"
  },
  {
    "k": "ultra_male",
    "name": "Ultra Male",
    "brand": "Jean Paul Gaultier",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Ambarada frutal",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/ultra_male.webp",
    "desc": "Pera jugosa, lavanda y vainilla negra. Dulce, intenso y con una estela que no pasa desapercibida.",
    "top": "Pera · Lavanda · Menta",
    "heart": "Canela · Salvia · Comino",
    "base": "Vainilla negra · Ámbar · Pachulí",
    "il": "Presentación",
    "insp": "Original · consultá presentaciones"
  },
  {
    "k": "lebeau_parfum",
    "name": "Le Beau Le Parfum",
    "brand": "Jean Paul Gaultier",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Ambarada tropical",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/lebeau_parfum.webp",
    "desc": "Piña y coco con un fondo cálido de haba tonka y sándalo. Tropical, sensual e intenso.",
    "top": "Piña · Iris · Ciprés · Jengibre",
    "heart": "Coco · Notas amaderadas",
    "base": "Haba tonka · Sándalo · Ámbar",
    "il": "Presentación",
    "insp": "Original · consultá presentaciones"
  },
  {
    "k": "lebeau_narcisse",
    "name": "Le Beau Narcisse",
    "brand": "Jean Paul Gaultier",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Floral almizclada",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/lebeau_narcisse.webp",
    "desc": "Coco y bergamota sobre azahar, almizcle y vainilla. Suave, limpio y cremoso: el lanzamiento 2026 de la línea Le Beau.",
    "top": "Bergamota · Coco",
    "heart": "Flor de azahar · Almizcle",
    "base": "Vainilla · Haba tonka · Vetiver",
    "il": "Presentación",
    "insp": "Original · consultá presentaciones"
  },
  {
    "k": "polo_blue",
    "name": "Polo Blue",
    "brand": "Ralph Lauren",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Acuática aromática",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/polo_blue.webp",
    "desc": "Pepino, melón y albahaca con un fondo de gamuza. Fresco, relajado y fácil de usar todo el año.",
    "top": "Pepino · Melón · Mandarina",
    "heart": "Albahaca · Salvia · Geranio",
    "base": "Gamuza · Notas amaderadas · Almizcle",
    "il": "Presentación",
    "insp": "Original · 125 ml"
  },
  {
    "k": "polo_black",
    "name": "Polo Black",
    "brand": "Ralph Lauren",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Amaderada frutal",
    "cat": "amaderado",
    "encargue": false,
    "img": "img/perfumes/polo_black.webp",
    "desc": "Mango helado y salvia sobre pachulí y sándalo. Sofisticado, suave y distinto.",
    "top": "Mango helado · Mandarina · Limón",
    "heart": "Artemisa plateada · Salvia",
    "base": "Pachulí · Sándalo · Haba tonka",
    "il": "Presentación",
    "insp": "Original · 125 ml"
  },
  {
    "k": "chance_splendide",
    "name": "Chance Eau Splendide",
    "brand": "Chanel",
    "seccion": "disenador",
    "genero": "mujer",
    "fam": "Floral frutal",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/chance_splendide.webp",
    "desc": "Frambuesa, rosa y violeta con un fondo de almizcles blancos. Luminoso, femenino y muy Chanel.",
    "top": "Frambuesa · Rosa · Violeta",
    "heart": "Geranio · Iris",
    "base": "Almizcles blancos · Cedro",
    "il": "Presentación",
    "insp": "Original · 100 ml"
  },
  {
    "k": "light_blue_edp",
    "name": "Light Blue EDP",
    "brand": "Dolce & Gabbana",
    "seccion": "disenador",
    "genero": "mujer",
    "fam": "Cítrica ambarada",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/light_blue_edp.webp",
    "desc": "El espíritu mediterráneo de Light Blue en eau de parfum: limón siciliano, flores cálidas y maderas ambaradas.",
    "top": "Limón siciliano · Bergamota · Pimienta rosa",
    "heart": "Frangipani · Caléndula · Canela",
    "base": "Amberwood · Benjuí",
    "il": "Presentación",
    "insp": "Original · 100 ml"
  },
  {
    "k": "leau_dissey",
    "name": "L'Eau d'Issey EDP",
    "brand": "Issey Miyake",
    "seccion": "disenador",
    "genero": "mujer",
    "fam": "Floral acuática",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/leau_dissey.webp",
    "desc": "Loto y flores blancas con un fondo de maderas suaves. Puro, delicado y atemporal.",
    "top": "Loto · Fresia · Ciclamen",
    "heart": "Peonía · Lirio · Clavel",
    "base": "Cedro · Sándalo · Almizcle",
    "il": "Presentación",
    "insp": "Original · 100 ml"
  },
  {
    "k": "very_good_girl",
    "name": "Very Good Girl",
    "brand": "Carolina Herrera",
    "seccion": "disenador",
    "genero": "mujer",
    "fam": "Floral frutal",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/very_good_girl.webp",
    "desc": "Grosella roja y lichi sobre un corazón de rosa y fondo de vainilla. Atrevido, jugoso y muy femenino.",
    "top": "Grosella roja · Lichi",
    "heart": "Rosa",
    "base": "Vainilla · Vetiver",
    "il": "Presentación",
    "insp": "Original · consultá presentaciones"
  },
  {
    "k": "good_girl_jasmine",
    "name": "Good Girl Jasmine Absolute",
    "brand": "Carolina Herrera",
    "seccion": "disenador",
    "genero": "mujer",
    "fam": "Floral gourmand",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/good_girl_jasmine.webp",
    "desc": "Jazmín y almendra amarga con un fondo de toffee y haba tonka. La nueva versión golosa y elegante de Good Girl.",
    "top": "Mandarina · Grosella negra",
    "heart": "Jazmín · Almendra amarga",
    "base": "Toffee caramelizado · Haba tonka",
    "il": "Presentación",
    "insp": "Original · consultá presentaciones"
  },
  {
    "k": "la_bomba",
    "name": "La Bomba",
    "brand": "Carolina Herrera",
    "seccion": "disenador",
    "genero": "mujer",
    "fam": "Floral tropical",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/la_bomba.webp",
    "desc": "Pitahaya y ananá con peonía roja y un fondo de vainilla. Alegre, vibrante y con mucha personalidad.",
    "top": "Pitahaya · Ananá · Mandarina",
    "heart": "Frangipani · Peonía roja · Flor de azahar",
    "base": "Vainilla · Pachulí · Haba tonka",
    "il": "Presentación",
    "insp": "Original · consultá presentaciones"
  },
  {
    "k": "libre_edp",
    "name": "Libre EDP",
    "brand": "Yves Saint Laurent",
    "seccion": "disenador",
    "genero": "mujer",
    "fam": "Floral ambarada",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/libre_edp.webp",
    "desc": "Lavanda y flor de azahar sobre vainilla de Madagascar. Elegante, potente y de los más elogiados de YSL.",
    "top": "Lavanda · Mandarina · Grosella negra",
    "heart": "Flor de azahar · Jazmín",
    "base": "Vainilla de Madagascar · Almizcle · Cedro",
    "il": "Presentación",
    "insp": "Original · consultá presentaciones"
  },
  {
    "k": "scandal_edp",
    "name": "Scandal EDP",
    "brand": "Jean Paul Gaultier",
    "seccion": "disenador",
    "genero": "mujer",
    "fam": "Floral amielada",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/scandal_edp.webp",
    "desc": "Miel y gardenia con naranja sanguina y un fondo de pachulí. Dulce, sensual y de gran estela.",
    "top": "Naranja sanguina · Mandarina",
    "heart": "Miel · Gardenia · Flor de azahar",
    "base": "Cera de abejas · Caramelo · Pachulí",
    "il": "Presentación",
    "insp": "Original · consultá presentaciones"
  },
  {
    "k": "scandal_parfum",
    "name": "Scandal Le Parfum",
    "brand": "Jean Paul Gaultier",
    "seccion": "disenador",
    "genero": "mujer",
    "fam": "Floral gourmand",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/scandal_parfum.webp",
    "desc": "Jazmín con caramelo salado y vainilla. La versión más intensa y adictiva de Scandal.",
    "top": "Jazmín",
    "heart": "Caramelo salado",
    "base": "Vainilla",
    "il": "Presentación",
    "insp": "Original · consultá presentaciones"
  },
  {
    "k": "miss_dior_blooming",
    "name": "Miss Dior Blooming Bouquet",
    "brand": "Dior",
    "seccion": "disenador",
    "genero": "mujer",
    "fam": "Floral fresca",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/miss_dior_blooming.webp",
    "desc": "Peonía y rosa con un toque cítrico y fondo de almizcle blanco. Delicado, romántico y fácil de llevar.",
    "top": "Bergamota · Mandarina",
    "heart": "Peonía · Rosa damascena",
    "base": "Almizcle blanco",
    "il": "Presentación",
    "insp": "Original · consultá presentaciones"
  },
  {
    "k": "issey_homme",
    "name": "L'Eau d'Issey Pour Homme",
    "brand": "Issey Miyake",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Acuática cítrica",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/issey_homme.webp",
    "desc": "Yuzu y cítricos chispeantes sobre maderas y especias suaves. Un clásico fresco, limpio y muy reconocible.",
    "top": "Yuzu · Limón · Bergamota",
    "heart": "Nuez moscada · Loto azul · Geranio",
    "base": "Sándalo · Cedro · Vetiver",
    "il": "Presentación",
    "insp": "Original · consultá presentaciones"
  },
  {
    "k": "vip_black",
    "name": "212 VIP Black",
    "brand": "Carolina Herrera",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Aromática fougère",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/vip_black.webp",
    "desc": "Absenta y anís sobre vainilla negra y almizcle. Nocturno, magnético y de mucha personalidad.",
    "top": "Absenta · Anís · Hinojo",
    "heart": "Lavanda",
    "base": "Vainilla negra · Almizcle",
    "il": "Presentación",
    "insp": "Original · 100 ml"
  },
  {
    "k": "erba_pura",
    "name": "Erba Pura",
    "brand": "Xerjoff",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Frutal ambarada",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/erba_pura.webp",
    "desc": "Explosión de cítricos y frutas sobre vainilla y almizcle blanco. Perfumería de nicho de enorme proyección.",
    "top": "Naranja siciliana · Bergamota · Limón",
    "heart": "Frutas",
    "base": "Almizcle blanco · Vainilla · Ámbar",
    "il": "Presentación",
    "insp": "Original · 100 ml"
  },
  {
    "k": "explorer",
    "name": "Explorer EDP",
    "brand": "Montblanc",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Amaderada aromática",
    "cat": "amaderado",
    "encargue": false,
    "img": "img/perfumes/explorer.webp",
    "desc": "Bergamota, vetiver y pachulí con un toque de cuero. Versátil, masculino y de gran rendimiento.",
    "top": "Bergamota · Pimienta rosa · Salvia",
    "heart": "Vetiver · Cuero",
    "base": "Ambroxan · Pachulí · Cacao",
    "il": "Presentación",
    "insp": "Original · consultá presentaciones"
  },
  {
    "k": "explorer_platinum",
    "name": "Explorer Platinum",
    "brand": "Montblanc",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Fougère amaderada",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/explorer_platinum.webp",
    "desc": "Hoja de violeta y lima con un corazón aromático y fondo de cedro. Fresco, metálico y elegante.",
    "top": "Hoja de violeta · Lima · Pimienta rosa",
    "heart": "Salvia · Geranio bourbon",
    "base": "Cedro de Alaska · Ambrox · Musgo de roble",
    "il": "Presentación",
    "insp": "Original · consultá presentaciones"
  },
  {
    "k": "explorer_extreme",
    "name": "Explorer Extreme",
    "brand": "Montblanc",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Amaderada ambarada",
    "cat": "amaderado",
    "encargue": false,
    "img": "img/perfumes/explorer_extreme.webp",
    "desc": "La versión más intensa de Explorer: bergamota, pachulí y un ámbar cálido en concentración parfum.",
    "top": "Bergamota",
    "heart": "Pachulí",
    "base": "Ámbar cálido",
    "il": "Presentación",
    "insp": "Original · consultá presentaciones"
  },
  {
    "k": "paradigme",
    "name": "Paradigme EDP",
    "brand": "Prada",
    "seccion": "disenador",
    "genero": "hombre",
    "fam": "Ambarada amaderada",
    "cat": "amaderado",
    "encargue": false,
    "img": "img/perfumes/paradigme.webp",
    "desc": "Bergamota luminosa, geranio y maderas ambaradas. Cálido y fresco a la vez, el nuevo masculino de Prada.",
    "top": "Bergamota de Calabria",
    "heart": "Geranio bourbon",
    "base": "Maderas ambaradas",
    "il": "Presentación",
    "insp": "Original · consultá presentaciones"
  }
];
