// ============================================================
//  PERFUMES DE LA COLECCIÓN — Al Eutur Perfumes
//  Cada bloque { ... } es una ficha. El orden de esta lista es
//  el orden en que aparecen en la web.
//
//  cat      : fresco | oriental | amaderado | gourmand   (filtro)
//  encargue : true muestra la etiqueta "Por encargue"
//  img      : foto en img/perfumes/  (fondo transparente, .webp)
//  il/insp  : "Inspirado en" + perfume de referencia
//
//  Instrucciones completas en el README.md
// ============================================================
window.PERFUMES = [
  {
    "k": "mandarin",
    "name": "Odyssey Mandarin Sky",
    "brand": "Armaf",
    "fam": "Cítrica dulce",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/mandarin.webp",
    "desc": "Mandarina fresca y azafrán dan paso a un fondo de caramelo suave. Adictivo, luminoso, ideal para el día.",
    "top": "Mandarina · Notas verdes",
    "heart": "Azafrán · Flor de naranjo",
    "base": "Caramelo · Almizcle · Cedro",
    "il": "Inspirado en",
    "insp": "Scandal Pour Homme · Jean Paul Gaultier"
  },
  {
    "k": "spectra",
    "name": "Odyssey Spectra",
    "brand": "Armaf",
    "fam": "Oriental especiada",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/spectra.webp",
    "desc": "Manzana y canela envuelven un corazón de tabaco especiado. Dulce, magnético, pensado para la noche.",
    "top": "Manzana · Canela",
    "heart": "Tabaco · Especias",
    "base": "Vainilla · Ámbar · Maderas",
    "il": "Inspirado en",
    "insp": "Le Male Le Parfum · Jean Paul Gaultier"
  },
  {
    "k": "homme",
    "name": "Odyssey Homme",
    "brand": "Armaf",
    "fam": "Oriental amaderada",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/homme.webp",
    "desc": "Cardamomo y sándalo sobre un fondo cálido de vainilla y ámbar. Elegante, envolvente, para ocasiones nocturnas.",
    "top": "Cardamomo · Bergamota",
    "heart": "Sándalo · Especias",
    "base": "Vainilla · Ámbar · Cachemira",
    "il": "Inspirado en",
    "insp": "Noir Extreme · Tom Ford"
  },
  {
    "k": "dubai",
    "name": "Odyssey Dubai Chocolat",
    "brand": "Armaf",
    "fam": "Gourmand",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/dubai.webp",
    "desc": "El postre viral hecho perfume. Pistacho cremoso, café y praliné sobre un fondo dulce y envolvente.",
    "top": "Pistacho · Café",
    "heart": "Praliné · Cacao",
    "base": "Caramelo · Haba tonka · Amberwood",
    "il": "Inspiración",
    "insp": "El famoso chocolate de Dubái"
  },
  {
    "k": "honor",
    "name": "Honor & Glory",
    "brand": "Lattafa",
    "fam": "Ámbar gourmand",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/honor.webp",
    "desc": "Piña jugosa y crème brûlée sobre un fondo ambarado. Unisex, dulce con presencia, para todo el año.",
    "top": "Piña · Bergamota",
    "heart": "Crème brûlée · Flores blancas",
    "base": "Ámbar · Almizcle · Maderas",
    "il": "Inspiración",
    "insp": "Gourmand ámbar de firma"
  },
  {
    "k": "toscano",
    "name": "Toscano Leather",
    "brand": "Maison Alhambra",
    "fam": "Cuero",
    "cat": "amaderado",
    "encargue": false,
    "img": "img/perfumes/toscano.webp",
    "desc": "Cuero intenso realzado por azafrán y un toque de frambuesa. Elegante, de carácter, para la noche o el frío.",
    "top": "Azafrán · Tomillo",
    "heart": "Cuero · Frambuesa · Incienso",
    "base": "Cuero · Ámbar",
    "il": "Inspirado en",
    "insp": "Tuscan Leather · Tom Ford"
  },
  {
    "k": "bharara",
    "name": "Bharara King",
    "brand": "Bharara",
    "fam": "Aromática afrutada",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/bharara.webp",
    "desc": "Cítricos radiantes sobre un fondo dulce y ambarado. Proyección enorme, unisex, para destacar en cualquier evento.",
    "top": "Bergamota · Cítricos",
    "heart": "Frutas · Flores blancas",
    "base": "Vainilla · Ámbar · Almizcle",
    "il": "Inspirado en",
    "insp": "Erba Pura · Xerjoff"
  },
  {
    "k": "yeah",
    "name": "Yeah! Parfum",
    "brand": "Maison Alhambra",
    "fam": "Ámbar aromática",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/yeah.webp",
    "desc": "Manzana y jengibre dan paso a un fondo cálido de ámbar y tonka. Más intenso que la versión EDP, ideal para clima fresco.",
    "top": "Manzana · Jengibre",
    "heart": "Lavanda · Especias",
    "base": "Ámbar · Haba tonka · Maderas",
    "il": "Inspirado en",
    "insp": "Y Le Parfum · Yves Saint Laurent"
  },
  {
    "k": "sceptre",
    "name": "Sceptre Malachite",
    "brand": "Maison Alhambra",
    "fam": "Amaderada verde",
    "cat": "amaderado",
    "encargue": false,
    "img": "img/perfumes/sceptre.webp",
    "desc": "Verde aromático sobrio con fondo de vetiver y pachulí. Atemporal, ideal para oficina y uso diario.",
    "top": "Bergamota · Notas verdes",
    "heart": "Geranio · Especias",
    "base": "Vetiver · Pachulí · Maderas",
    "il": "Inspirado en",
    "insp": "Le Gemme Malachite · Bvlgari"
  },
  {
    "k": "baroque",
    "name": "Baroque Rouge 540",
    "brand": "Maison Alhambra",
    "fam": "Ámbar floral",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/baroque.webp",
    "desc": "La estela más reconocida del mundo, reinterpretada. Azafrán y jazmín sobre amberwood cálido. El más deseado de la casa.",
    "top": "Azafrán · Jazmín",
    "heart": "Amberwood · Flores blancas",
    "base": "Ámbar gris · Cedro",
    "il": "Inspirado en",
    "insp": "Baccarat Rouge 540 · Maison Francis Kurkdjian"
  },
  {
    "k": "victorioso",
    "name": "Victorioso",
    "brand": "Maison Alhambra",
    "fam": "Aromática acuática amaderada",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/victorioso.webp",
    "desc": "Pomelo y notas marinas abren con frescura vibrante sobre una base amaderada. Enérgico y versátil para el día.",
    "top": "Pomelo · Notas marinas",
    "heart": "Laurel · Jazmín · Hedione",
    "base": "Gaiac · Musgo de roble · Ámbar gris",
    "il": "Inspirado en",
    "insp": "Invictus · Paco Rabanne"
  },
  {
    "k": "tag",
    "name": "Tag Uomo Nero",
    "brand": "Armaf",
    "fam": "Amaderada aromática",
    "cat": "amaderado",
    "encargue": false,
    "img": "img/perfumes/tag.webp",
    "desc": "Apertura especiada con un corazón floral inesperado de violeta y rosa. Elegante y versátil, mejora con maceración.",
    "top": "Bergamota · Pimienta negra · Lavanda",
    "heart": "Lirio del valle · Violeta · Rosa",
    "base": "Pachulí · Ámbar gris · Vainilla",
    "il": "Inspirado en",
    "insp": "Tuxedo · Yves Saint Laurent"
  },
  {
    "k": "yara",
    "name": "Yara",
    "brand": "Lattafa",
    "fam": "Vainilla gourmand",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/yara.webp",
    "desc": "Dulce, cremoso y afrutado desde el primer instante. El favorito femenino de Lattafa, coqueto y fácil de llevar.",
    "top": "Mandarina · Orquídea · Heliotropo",
    "heart": "Acorde gourmand · Frutas tropicales",
    "base": "Vainilla · Musk · Sándalo",
    "il": "Inspiración",
    "insp": "Creación de firma · el gourmand femenino más vendido de Lattafa"
  },
  {
    "k": "salvo",
    "name": "Salvo Elixir",
    "brand": "Maison Alhambra",
    "fam": "Aromática especiada",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/salvo.webp",
    "desc": "Especiado y potente desde el primer momento. Canela y cardamomo sobre un fondo ambarado, para clima frío.",
    "top": "Canela · Cardamomo",
    "heart": "Lavanda · Especias",
    "base": "Ámbar · Maderas · Almizcle",
    "il": "Inspirado en",
    "insp": "Sauvage Elixir · Dior"
  },
  {
    "k": "mega",
    "name": "Odyssey Mega",
    "brand": "Armaf",
    "fam": "Aromática amaderada",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/mega.webp",
    "desc": "Fresco, limpio y fácil de llevar. Jengibre y cítricos sobre un fondo suave de cedro. Ideal día a día.",
    "top": "Jengibre · Bergamota · Cítricos",
    "heart": "Piña · Salvia · Enebro",
    "base": "Almizcle · Cedro · Haba tonka",
    "il": "Inspirado en",
    "insp": "Y Eau de Parfum · Yves Saint Laurent"
  },
  {
    "k": "momento",
    "name": "Momento",
    "brand": "Riiffs",
    "fam": "Amaderada especiada",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/momento.webp",
    "desc": "Azafrán y rosa sobre un fondo dulce de tonka. Amaderado y elegante, con gran duración.",
    "top": "Azafrán · Rosa",
    "heart": "Especias · Flores",
    "base": "Haba tonka · Maderas · Ámbar",
    "il": "Inspirado en",
    "insp": "Arabians Tonka · Montale"
  },
  {
    "k": "clubdenuit",
    "name": "Club de Nuit Intense Man",
    "brand": "Armaf",
    "fam": "Amaderada ahumada",
    "cat": "amaderado",
    "encargue": false,
    "img": "img/perfumes/clubdenuit.webp",
    "desc": "Piña y frutas abren paso a un fondo ahumado de abedul. Intenso y versátil, con proyección excepcional en modo bestia.",
    "top": "Piña · Manzana · Bergamota",
    "heart": "Abedul · Jazmín",
    "base": "Almizcle · Ámbar · Maderas",
    "il": "Inspirado en",
    "insp": "Aventus · Creed"
  },
  {
    "k": "asadelixir",
    "name": "Asad Elixir",
    "brand": "Lattafa",
    "fam": "Oriental ahumada",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/asadelixir.webp",
    "desc": "Azafrán y tabaco sobre un fondo de incienso y ámbar seco. Nocturno y elegante, para las estaciones frías.",
    "top": "Pimienta rosa · Azafrán · Pomelo",
    "heart": "Tabaco · Cedro · Vainilla",
    "base": "Incienso · Ámbar · Pachulí",
    "il": "Inspiración",
    "insp": "Perfil ahumado y especiado, ideal para clima frío"
  },
  {
    "k": "asadbourbon",
    "name": "Asad Bourbon",
    "brand": "Lattafa",
    "fam": "Ámbar gourmand",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/asadbourbon.webp",
    "desc": "Cacao y vainilla bourbon envuelven un corazón especiado. Cálido, dulce y unisex, perfecto para el invierno.",
    "top": "Lavanda · Ciruela · Pimienta rosa",
    "heart": "Cacao · Nuez moscada · Davana",
    "base": "Vainilla bourbon · Ámbar · Vetiver",
    "il": "Inspiración",
    "insp": "Cálido y goloso, ideal para noches frescas"
  },
  {
    "k": "cdnwoman",
    "name": "Club de Nuit Woman",
    "brand": "Armaf",
    "fam": "Chipre floral",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/cdnwoman.webp",
    "desc": "Cítrico chispeante sobre rosa y pachulí. Fresco, elegante y sofisticado, de día o de noche. Para damas.",
    "top": "Naranja · Bergamota · Toronja",
    "heart": "Rosa · Pachulí",
    "base": "Almizcle · Maderas",
    "il": "Inspirado en",
    "insp": "Coco Mademoiselle · Chanel"
  },
  {
    "k": "cdnintensew",
    "name": "Club de Nuit Intense Woman",
    "brand": "Armaf",
    "fam": "Floral oriental",
    "cat": "oriental",
    "encargue": false,
    "img": "img/perfumes/cdnintensew.webp",
    "desc": "La versión femenina del clásico Intense: rosa, azafrán y oud. Estela fuerte, ideal para la noche. Para damas.",
    "top": "Rosa · Fresco especiado",
    "heart": "Azafrán · Pachulí",
    "base": "Oud · Vainilla · Ámbar",
    "il": "Inspirado en",
    "insp": "Noir de Noir · Tom Ford"
  },
  {
    "k": "maleka",
    "name": "Club de Nuit Maleka",
    "brand": "Armaf",
    "fam": "Floral frutal",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/maleka.webp",
    "desc": "Lichi jugoso e iris atalcado sobre un fondo de praliné y sándalo. Dulce y refinado, 7 h de duración. Para damas.",
    "top": "Lichi · Bergamota",
    "heart": "Iris · Raíz de lirio",
    "base": "Praliné · Sándalo · Ambroxan",
    "il": "Inspirado en",
    "insp": "Delina · Parfums de Marly"
  },
  {
    "k": "untold",
    "name": "Club de Nuit Untold",
    "brand": "Armaf",
    "fam": "Ámbar amaderado",
    "cat": "amaderado",
    "encargue": false,
    "img": "img/perfumes/untold.webp",
    "desc": "Azafrán y ámbar gris sobre maderas luminosas. Unisex, dulce y metálico, con 8 h de duración y estela fuerte.",
    "top": "Azafrán · Jazmín",
    "heart": "Madera de ámbar · Ámbar gris",
    "base": "Cedro · Abeto",
    "il": "Inspirado en",
    "insp": "Baccarat Rouge 540 · MFK"
  },
  {
    "k": "iconic",
    "name": "Club de Nuit Blue Iconic",
    "brand": "Armaf",
    "fam": "Amaderada fresca",
    "cat": "fresco",
    "encargue": false,
    "img": "img/perfumes/iconic.webp",
    "desc": "Cítricos y menta sobre maderas secas e incienso. Fresco, versátil y masculino. Frasco de 125 ml.",
    "top": "Pomelo · Limón · Menta",
    "heart": "Jengibre · Pimienta rosa",
    "base": "Incienso · Sándalo · Cedro",
    "il": "Inspirado en",
    "insp": "Bleu de Chanel · Chanel"
  },
  {
    "k": "yaramoi",
    "name": "Yara Moi",
    "brand": "Lattafa",
    "fam": "Floral amaderada",
    "cat": "amaderado",
    "encargue": false,
    "img": "img/perfumes/yaramoi.webp",
    "desc": "La Yara blanca: jazmín y durazno sobre sándalo y caramelo. Más elegante y versátil que el resto de la línea. Para damas.",
    "top": "Jazmín · Durazno",
    "heart": "Pachulí · Cálido especiado",
    "base": "Sándalo · Caramelo · Ámbar",
    "il": "Inspirado en",
    "insp": "Perfect Intense · Marc Jacobs"
  },
  {
    "k": "yaraelixir",
    "name": "Yara Elixir",
    "brand": "Lattafa",
    "fam": "Oriental vainilla",
    "cat": "gourmand",
    "encargue": false,
    "img": "img/perfumes/yaraelixir.webp",
    "desc": "El más goloso de la línea Yara: frutilla, caramelo y vainilla. Dulce, envolvente y de estela fuerte. Para damas.",
    "top": "S'mores de frutilla · Grosella negra",
    "heart": "Caramelo · Floral blanco",
    "base": "Vainilla · Ámbar · Almizcle",
    "il": "Inspirado en",
    "insp": "Black Opium · YSL"
  },
  {
    "k": "khamrah",
    "name": "Khamrah",
    "brand": "Lattafa",
    "fam": "Oriental gourmand",
    "cat": "gourmand",
    "encargue": true,
    "img": "img/perfumes/khamrah.webp",
    "desc": "Dátiles y canela sobre un fondo de praliné y vainilla. Dulce, cálido y envolvente. Disponible por encargue.",
    "top": "Dátiles · Canela",
    "heart": "Praliné · Especias",
    "base": "Vainilla · Ámbar · Maderas",
    "il": "Inspiración",
    "insp": "Creación de firma de la línea Khamrah"
  },
  {
    "k": "khamrah_qahwa",
    "name": "Khamrah Qahwa",
    "brand": "Lattafa",
    "fam": "Oriental vainilla",
    "cat": "gourmand",
    "encargue": true,
    "img": "img/perfumes/khamrah_qahwa.webp",
    "desc": "Café y cardamomo sobre vainilla y tonka. Cálido y adictivo. Disponible por encargue.",
    "top": "Café · Cardamomo",
    "heart": "Praliné · Especias",
    "base": "Vainilla · Tonka · Maderas",
    "il": "Inspiración",
    "insp": "Variante café de la línea Khamrah"
  },
  {
    "k": "khamrah_dukhan",
    "name": "Khamrah Dukhan",
    "brand": "Lattafa",
    "fam": "Oriental ahumado",
    "cat": "oriental",
    "encargue": true,
    "img": "img/perfumes/khamrah_dukhan.webp",
    "desc": "Ahumado y de carácter, con tabaco e incienso sobre fondo amaderado. Oscuro y elegante. Disponible por encargue.",
    "top": "Especias · Ahumado",
    "heart": "Tabaco · Incienso",
    "base": "Maderas · Ámbar",
    "il": "Inspiración",
    "insp": "Variante ahumada de la línea Khamrah"
  },
  {
    "k": "khamrah_waha",
    "name": "Khamrah Waha",
    "brand": "Lattafa",
    "fam": "Fresco acuático",
    "cat": "fresco",
    "encargue": true,
    "img": "img/perfumes/khamrah_waha.webp",
    "desc": "El más ligero e inesperado de la línea Khamrah: fresco y acuático. Novedad 2026. Disponible por encargue.",
    "top": "Notas acuáticas · Cítricos",
    "heart": "Flores blancas",
    "base": "Almizcle · Maderas claras",
    "il": "Inspiración",
    "insp": "La variante fresca que rompe el ADN cálido de la línea"
  },
  {
    "k": "aquadubai",
    "name": "Amber Oud Aqua Dubai",
    "brand": "Al Haramain",
    "fam": "Ámbar acuático",
    "cat": "fresco",
    "encargue": true,
    "img": "img/perfumes/aquadubai.webp",
    "desc": "Fresco y ambarado, con una firma acuática distintiva. Elegante y luminoso. Disponible por encargue, 100ml.",
    "top": "Cítricos · Notas acuáticas",
    "heart": "Flores",
    "base": "Ámbar · Maderas",
    "il": "Inspirado en",
    "insp": "Imagination · Louis Vuitton"
  },
  {
    "k": "goldedition",
    "name": "Amber Oud Gold Edition",
    "brand": "Al Haramain",
    "fam": "Ámbar afrutado",
    "cat": "oriental",
    "encargue": true,
    "img": "img/perfumes/goldedition.webp",
    "desc": "Cítricos y frutas sobre vainilla y ámbar cálido. Dulce y radiante. Disponible por encargue, 100ml.",
    "top": "Cítricos · Frutas",
    "heart": "Flores blancas",
    "base": "Vainilla · Ámbar · Maderas",
    "il": "Inspirado en",
    "insp": "Erba Pura · Xerjoff"
  }
];
